<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>ClassEnrollment</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Class__c.Contact__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Class__c.Date_Offered__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Class__c.Facility__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Class__c.Max_Capacity__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Class__c.Product2__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Enrollment__c.Class__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SFDC_Enrollment__c.Contact__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>SFDC_Enrollment__c.Status__c</field>
    </fieldLevelSecurities>
    <layoutAssignments>
        <layout>SFDC_Class__c-Class Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>SFDC_Enrollment__c-Enrollment Layout</layout>
    </layoutAssignments>
    <objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <object>SFDC_Class__c</object>
    </objectPermissions>
    <objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <object>SFDC_Enrollment__c</object>
    </objectPermissions>
    <tabVisibilities>
        <tab>AboutClassEnrollment</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>SFDC_Class__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>SFDC_Enrollment__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>
